services:
  - type: web
    name: horoscope-line-bot
    env: python
    region: singapore  # 或其他地區：oregon / frankfurt / ohio 等

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"

    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
